version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: isthereany-one-client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - /client/node_modules
    restart: "unless-stopped"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
      args:
        - PORT=${API_PORT}
    container_name: isthereany-one-api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - /api/node_modules
    restart: "unless-stopped"
